/*

 PHI
 2026/01/31

 Phi C++ Project
 include/encryption/asymmetric/kyber.hpp

 Zevi Berlin

*/

#ifndef KYBER_HPP
#define KYBER_HPP

#include <vector>
#include <array>
#include <string>
#include <cstdint>
#include <cstring>

#include "ml_kem/ml_kem_512.hpp"
#include "ml_kem/ml_kem_768.hpp"
#include "randomshake/randomshake.hpp"
#include "sha3/shake256.hpp"

//---------> [ Config. Separator ] <---------\\ 

namespace phi::encryption {

/*
Generate a public/private KYBER key pair
*/
void kyber512GenKeyPair(std::array<uint8_t, ml_kem_512::PKEY_BYTE_LEN>& op_public,
                        std::array<uint8_t, ml_kem_512::SKEY_BYTE_LEN>& op_private);

//================={ Header Item Separator }=================\\ 

/*
Generate a 32 byte shared secret and ciphertext

Returns false if an invalid public key

The shared secret should be derived into a symmetric key
 and never sent, only the ciphertext is sent in the JSON
*/
bool kyber512GenData(const std::array<uint8_t, ml_kem_512::PKEY_BYTE_LEN>& kyber_pub_key,
                     std::array<uint8_t, ml_kem_512::CIPHER_TEXT_BYTE_LEN>& op_ciphertext,
                     std::array<uint8_t, ml_kem_512::SHARED_SECRET_BYTE_LEN>& op_ss);


//================={ Header Item Separator }=================\\ 

/*
Derive from a ciphertext using a KYBER private
 key a shared secret

**IMPORTANT NOTE**
 Should decapsulation fail, there is no sign. It
  will effectively put just a random byte array into
  op_ss. This is on purpose and then these random
  bytes will naturally fail and when a symmetric key
  is derived from them, that key will fail and that's
  your signal of its failure
*/
void kyber512DeriveSS(const std::array<uint8_t, ml_kem_512::CIPHER_TEXT_BYTE_LEN>& ciphertext,
                      const std::array<uint8_t, ml_kem_512::SKEY_BYTE_LEN>& kyber_priv_key,
                      std::array<uint8_t, ml_kem_512::SHARED_SECRET_BYTE_LEN>& op_ss);

//================={ Header Item Separator }=================\\ 

/*
Use a shared secret generated by a KYBER key
 to derive a symmetric key of length key_size

Info should be a string that describes the algorithm
 for which the new key is, it should be a compile time
 constexpr like "aes-128" or "chacha20_poly1305"
*/
std::vector<uint8_t> kyber512DeriveKey(
  int key_size, const std::array<uint8_t, ml_kem_512::SHARED_SECRET_BYTE_LEN>& ss);
}  // namespace phi::encryption

#endif /* KYBER_HPP */
