/*

 PHI
 2026/01/31

 Phi C++ Project
 include/encryption/asymmetric/kyber.hpp

 Zevi Berlin

*/

#ifndef KYBER_HPP
#define KYBER_HPP

#include <vector>
#include <array>
#include <string>
#include <cstdint>
#include <cstring>

#include "ml_kem/ml_kem_512.hpp"
#include "ml_kem/ml_kem_768.hpp"
#include "randomshake/randomshake.hpp"
#include "sha3/shake256.hpp"

//---------> [ Config. Separator ] <---------\\ 

namespace phi::encryption {

/*
Generate a public/private KYBER key pair

template type should be either ml_kem_512 or ml_kem_768
*/
template <typename MLKEM>
void kyberGenKeyPair(std::array<uint8_t, MLKEM::PKEY_BYTE_LEN>& op_public,
                     std::array<uint8_t, MLKEM::SKEY_BYTE_LEN>& op_private);

//================={ Header Item Separator }=================\\ 

/*
Generate a 32 byte shared secret and ciphertext

Returns false if an invalid public key

The shared secret should be derived into a symmetric key
 and never sent, only the ciphertext is sent in the JSON

template type should be either ml_kem_512 or ml_kem_768
*/
template <typename MLKEM>
bool kyberGenData(const std::array<uint8_t, MLKEM::PKEY_BYTE_LEN>& kyber_pub_key,
                  std::array<uint8_t, MLKEM::CIPHER_TEXT_BYTE_LEN>& op_ciphertext,
                  std::array<uint8_t, MLKEM::SHARED_SECRET_BYTE_LEN>& op_ss);

//================={ Header Item Separator }=================\\ 

/*
Derive from a ciphertext using a KYBER private
 key a shared secret

**IMPORTANT NOTE**
 Should decapsulation fail, there is no sign. It
  will effectively put just a random byte array into
  op_ss. This is on purpose and then these random
  bytes will naturally fail and when a symmetric key
  is derived from them, that key will fail and that's
  your signal of its failure

template type should be either ml_kem_512 or ml_kem_768
*/
template <typename MLKEM>
forceinline void kyberDeriveSS(const std::array<uint8_t, MLKEM::CIPHER_TEXT_BYTE_LEN>& ciphertext,
                               const std::array<uint8_t, MLKEM::SKEY_BYTE_LEN>& kyber_priv_key,
                               std::array<uint8_t, MLKEM::SHARED_SECRET_BYTE_LEN>& op_ss) {
  //
  ml_kem_512::decapsulate(kyber_priv_key, ciphertext, op_ss);
}

//================={ Header Item Separator }=================\\ 

/*
Use a shared secret generated by a KYBER key
 to derive a symmetric key of length key_size

Info should be a string that describes the algorithm
 for which the new key is, it should be a compile time
 constexpr like "aes-128" or "chacha20_poly1305"

template type should be either ml_kem_512 or ml_kem_768
*/
template <typename MLKEM>
std::vector<uint8_t> kyberDeriveKey(int key_size, const std::string& context,
                                    const std::array<uint8_t, MLKEM::SHARED_SECRET_BYTE_LEN>& ss);


#include "encryption/asymmetric/kyber.tpp"  // where all of these template functions are implemented
}  // namespace phi::encryption

#endif /* KYBER_HPP */
