.TH phi 1 "15 February 2026" "version 0.3.1"

.SH NAME
phi - Quantum-Safe TUI Encryption/Decryption Tool with a Contact Book (https://www.github.com/the-phi-project/phi)
 Named after Pheidippides (Φειδιππίδης) who ran 25 miles from Marathon to Athens in order to deliver a message.

.SH DESCRIPTION
phi is a powerful and efficient tool for encrypting and decrypting text and files to
.I safely
pass around on the internet. It's designed to operate in 2 ways: a TUI (Terminal User Interface), 
and as a CLI (Command Line Interface). In TUI mode you can utilize the app to its full capabilities
with encryption/decryption in all modes and creating/editing/deleting contacts and their keys.
However, in CLI mode it can only encrypt and decrypt messages based on contacts that already exist
(it can also list contacts' name and ID).

.SH SYNOPSIS
.B "phi [--list-contacts | --help]"

.B "phi [--encrypt] [--in-file|--str] [--contact-id] [--symmetric] [--asymmetric] [--out-file]"

.B "phi [--decrypt] [--in-file|--str] [--out-file]"

.SH OPTIONS (CLI Mode)

.B "-h, --help  "
Tells you to open this manpage

.B "--list-contacts  "
Use only this argument and no others to produce a list of contacts in the format `(ID) name`

.B "-e, --encrypt  "
Start encryption mode for the following arguments

.B "-d, --decrypt  "
Start decryption mode for the following arguments

.BI "-i, --in-file" " filepath  "
Take input from the file located at
.I filepath
.B " (Required UNLESS using the --str argument seen below)"

.BI "-s, --str" " \&"content\&"
.BR "" "  Use"
." ^this^ is for adding the two space buffer
.I content
as its input
.B " (Required UNLESS using the --in-file argument seen above)"

.BI "-o, --out-file" " filepath  "
Spit the output into the file located at
.I filepath
.B " (Not required, prints to the console by default)"

.BI "-s, --symmetric" " mode  "
Mode of symmetric encryption: aes128, aes192, aes256, twofish256, chacha20_poly1305

.BI "-a, --asymmetric" " mode  "
Mode of asymmetric encryption: rsa2048, rsa4096, kyber512, kyber768, kyber1024


.SH FILES
.I "$HOME/.phi/main.db     "
The main SQLite3 database that stores your keys and your contacts' keys.

.SH SEE ALSO
.B "All projects below are located at "
.I https://www.github.com/the-phi-project/

.I "Rephrigerator     "
A TUI password/secret vault

.I "VEIL     "
Virtual Environment for Invisible Logins: TUI/CLI anonymous ephemeral account creator

.I "Cloak     "
Antitracking Chrome extension for maximum privacy

.SH AUTHORS
.B "Zevi Berlin     <zeviberlin@gmail.com>"
